export const UPDATE_USER_NAME = 'UPDATE_USER_NAME';
export const UPDATE_RANDOM_USER = 'UPDATE_RANDOM_USER';
export const UPDATE_TRACKER_ID = 'UPDATE_TRACKER_ID';
export const UPDATE_CURRENT_LOCATION = 'UPDATE_CURRENT_LOCATION';
export const UPDATE_NETWORK_STATUS = 'UPDATE_NETWORK_STATUS';
